### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Duconnor** [Jia-Research-Lab/MiSLAS#1]
Hi! Thank you for such an inspiring work! Do you have any plan of releasing your code? I'm looking forward to that.

Plus, I have a small question regarding the method. In the paper you mentioned that when applying mixup in stage 2 yields no obvious improvement, but I cannot find a description of your overall method and I'd like to know in your final framework whether you use mixup in stage 1 only or in both stage 1&2. Thanks again!

**Comment by zs-zhong** [comment]
Hello, our current plan is to release the code in one or two weeks. Our paper is now available: https://arxiv.org/abs/2104.00466. According to Table 1 (Row-6 and 8), mixup has little improvement for decoupling models (both top-1 accuracy and ECE). Thus, in the final framework of MiSLAS, we just use mixup in Stage-1.

**Comment by Duconnor** [comment]
That's really helpful. Thank you very much!
