### ISSUE TITLE
About the BN part

### ISSUE THREAD

**Issue by tzhxs** [Jia-Research-Lab/MiSLAS#2]
Hi, thanks for your great work. I am wondering about the BN part, it seems that the methods like "cRT" and "DRW" do update the running mean and variances, right? I can not find the code segment which aims to freeze this part.

**Comment by zs-zhong** [comment]
Hello! Actually, in the final framework of "cRT", "LWS",  "DRS", and "DRW", they do update the running mean and variances in BN. While, in the "tau-norm" and "KNN" decoupling models, they don't update them. In our paper, we focus on the over-confidence issue. Due to the different class number composition ratios for the two stages, we believe the shifted BN would have some effects on the recognition performance and the calibration, which hasn't been discussed in previous two-stage methods. According to our experiment, it's proved.

**Comment by tzhxs** [comment]
> Hello! Actually, in the final framework of "cRT", "LWS", "DRS", and "DRW", they do update the running mean and variances in BN. While, in the "tau-norm" and "KNN" decoupling models, they don't update them. In our paper, we focus on the over-confidence issue. Due to the different class number composition ratios for the two stages, we believe the shifted BN could have some effects on the recognition performance and the calibration, which hasn't been discussed in previous two-stage methods. According to our experiment, it's proved.

So, acturally, the shifted BN is a widely used mehotd for "CRT", "LWS" also fixed the affine part?

**Comment by tzhxs** [comment]
> > Hello! Actually, in the final framework of "cRT", "LWS", "DRS", and "DRW", they do update the running mean and variances in BN. While, in the "tau-norm" and "KNN" decoupling models, they don't update them. In our paper, we focus on the over-confidence issue. Due to the different class number composition ratios for the two stages, we believe the shifted BN could have some effects on the recognition performance and the calibration, which hasn't been discussed in previous two-stage methods. According to our experiment, it's proved.
> 
> So, acturally, the shifted BN is a widely used mehotd for "CRT", "LWS" also fixed the affine part?

**Comment by tzhxs** [comment]
Is there something more details in the BN part of this paper?

**Comment by zs-zhong** [comment]
Yes, both "cRT" and "LWS" fix the affine part and update the running means and variances in Stage-2. For more details about the shifted BN, please refer to the experiment part. We also think a novel normalization to effectively deal with long-tailed recognition should be discussed and explored in the future.

**Comment by tzhxs** [comment]
> Yes, both "cRT" and "LWS" fix the affine part and update the running means and variances in Stage-2. For more details about the shifted BN, please refer to the experiment part. We also think a novel normalization to effectively deal with long-tailed recognition should be discussed and explored in the future.

Thanks, look forward to your new work
