### ISSUE TITLE
Shift Learning implementation

### ISSUE THREAD

**Issue by ZhiyuanDang** [Jia-Research-Lab/MiSLAS#3]
Hi, thanks for your works. However, in your paper, the implementation of shift learning has not been described detail. 

I guess that the BN parameters are re-trained in Stage-II, since the different means and variances. Is that true?

**Comment by zs-zhong** [comment]
Hello! The BN running parameters (running means and variances) are updated in Stage-II. We fix the BN affine parameters (alpha and beta) in Stage-II.

**Comment by ZhiyuanDang** [comment]
Thanks for your reply. 

'update' means reset the running means and variances in Stage-I or save them? And, which BN running parameters you adopted at the test phase?

**Comment by zs-zhong** [comment]
Hi, Zhiyuan, thanks for your interest! Concretely, in Stage-1, BN is trained on instance-balanced data (normal). The statistic running means and variances are <img src="https://render.githubusercontent.com/render/math?math=\mu_1, \sigma^2_1">, and the learnable affine parameters are <img src="https://render.githubusercontent.com/render/math?math=\alpha_1, \beta_1">. In Stage-2, we fix the learnable affine parameters <img src="https://render.githubusercontent.com/render/math?math=\alpha_1, \beta_1"> and momentum update <img src="https://render.githubusercontent.com/render/math?math=\mu_1, \sigma^2_1">. Finally, we get new  statistic running means and variances <img src="https://render.githubusercontent.com/render/math?math=\mu_2, \sigma^2_2"> on classes-balanced data (re-sample).  During the test phase, we adopt <img src="https://render.githubusercontent.com/render/math?math=\mu_2, \sigma^2_2"> and <img src="https://render.githubusercontent.com/render/math?math=\alpha_1, \beta_1"> for BN.

**Comment by ZhiyuanDang** [comment]
Thanks a lot for your detailed reply. I think it addresses my confusion.
