### ISSUE TITLE
Question about label-aware smoothing

### ISSUE THREAD

**Issue by Lucy0601** [Jia-Research-Lab/MiSLAS#4]
Hello:
In the paper, I think you mean nll_loss is only for the gt label and smooth_loss is for the remaining K-1 label.
But in the code
https://github.com/Jia-Research-Lab/MiSLAS/blob/e8f91e59a910c5543ea1bcabb955ba368c606a00/methods.py#L62
I think you still contain the gt label in the smooth_loss.
I am confusing about this.

**Comment by zs-zhong** [comment]
Hi, thank you for your interest! The code is slightly different from the equations mentioned in our paper. In fact, when the dataset contains more classes, there is not much difference. In our code, the weight for the GT label is confidence + smoothing / class_num.

**Comment by zs-zhong** [comment]
Hi, I will close this issue. If you have further confusion or question, you can reopen it again.
